/* vim: set tabstop=4 softtabstop=4 shiftwidth=4 expandtab: */

(function( Game, Settings, window, document, undefined ) {

var TILESIZE = Settings.tileSize;

var bl = 'blank',
    ld = 'terrain.land',
    wt = 'terrain.water',
    wv = 'terrain.wave',
    hm = 'hero.man',
    hb = 'hero.boat',
    hp = 'hero.plane',
    mn = 'enemy.monster',
    sp = 'enemy.spider',
    bd = 'enemy.bird',
    bs = 'enemy.battleship',
    ba = 'enemy.balloon',
    tr = 'enemy.turret',
    co = 'interactable.coin',
    ht = 'interactable.heart',
    rk = 'interactable.rock',
    td = function( id ) {
        return 'terrain.trapdoor(' + id + ')';
    },
    sw = function( id ) {
        return 'interactable.switch[6](' + id + ')';
    }

Game.Level = Class.extend({
    init: function( type, title, next, grid ) {
        var ents = {},
            i, j, entity;

        this.entities = [];
        this.title = title;
        this.type = type;
        this.width = TILESIZE * grid[0].length;
        this.height = TILESIZE * grid.length;
        this.next = next;
        this.grid = grid;
        for ( i in this.grid ) {
            for ( j in this.grid[ i ] ) {
                entity = this.grid[ i ][ j ];
                if ( !( entity in ents ) ) {
                    ents[ entity ] = entity;
                    this.entityCount++;
                }
            }
        }
    },
    loadNextLevel: function() {
        if ( this.next ) {
            Game.stop();
            Game.init( this.next );
        }
    }
});

Game.Levels = {
    'impressionism': new Game.Level( 'land', 'Impressionism', 'irontown', [
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, tr, ld ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, mn, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, ld, ld ],
        [ bl, bl, bl, bl, bl, bl, ht, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, tr, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, bl, bl, ld, ld, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, bl, bl, bl, bl, bl, bl, ld, ld, bl, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, mn, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, ld, bl, bl, bl, mn, ld, bl, bl, bl, bl, bl, bl, bl, mn, bl, bl, bl, mn, bl, bl, bl, tr, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, mn, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, rk, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, tr, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, tr, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, mn, bl, bl, mn, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ hm, bl, bl, co, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, mn, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, wv, wv, wv, wv, bl, bl, rk, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, tr, bl, bl, bl, bl, mn, bl, mn, bl, mn, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, tr, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, tr, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, wt, wt, wt, wt, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld ]
    ]),
    'the-cliffs-of-magnitude': new Game.Level( 'land', 'The Cliffs of Magnitude', 'fade-to-black', [
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bd, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, ld, ld, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, ld, ld, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, ld, ld ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, ld, ht, bl, bl, bl, bl, ld, ld, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ht, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl ],
        [ hm, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl ]
    ]),
    'fade-to-black': new Game.Level( 'land', 'Fade to Black', null, [
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, mn, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, mn, ld, ld, bl, bl, bl, bl, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, bl, bl, ld, td(1), ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, ld, ld, ld, bl, bl, sp, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, rk, bl, bl, sw(2), bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, td(2), td(2) ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, sp, bl, ld, bl, bl, bl, bl, sp, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, ld, bl, bl, bl, bl, ld, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bd, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, mn, bl, bl, mn, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, ld, ld, td(3), td(3), td(3), ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl ],
        [ bl, bl, bl, bl, bl, bl, bl, ld, bl, bl, bl, bl, sp, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, ld, bl, ld, bl, ld, bl, ld, bl, ld, bl, ld, bl, bl, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, bl, bl, bl, bl ],
        [ hm, bl, rk, sw(3), bl, bl, bl, ld, ht, bl, bl, bl, bl, mn, bl, ld, ld, ld, bl, bl, bl, bl, ld, ld, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, mn, bl, mn, bl, bl, bl, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, bl, bl, sw(1), bl, wv, wv, wv, wv, wv, bl, bl, tr, bl, ld, bl, ld, bl, ld, bl, ld, bl, ld, bl, ld, bl, bl, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, bl, bl, bl ],
        [ ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, wt, wt, wt, wt, wt, ld, ld, ld, ld, ld, bl, ld, bl, ld, bl, ld, bl, ld, bl, ld, bl, bl, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld, ld ]
    ])
};

})( Game, Settings, window, document );
