Settings.levelNameColor     = '#090300'; // 07 - Black
Settings.landBackground     = '#f7f7f7'; // 00 - Bright White
Settings.blackColor         = '#090300'; // 00 - Black
Settings.enemyColor         = '#db2d20'; // 08 - Red
Settings.heroColor          = '#01a252'; // 0B - Green
Settings.coinColor          = '#fded02'; // 0A - Yellow
Settings.waterColor         = '#01a0e4'; // 0D - Blue
Settings.heartColor         = '#a16a94'; // 0E - Magenta
Settings.tongueColor        = '#a16a94'; // 0E - Magenta
Settings.friendColor        = '#b5e4f4'; // 0C - Cyan
Settings.cloudColor         = '#f7f7f7'; // 07 - Bright White
Settings.landColor          = '#5c5855'; // 03 - Bright Black
Settings.rockColor          = '#807d7c'; // 04 - Grey
Settings.kidColor           = '#e8bbd0'; // 09 - Orange
Settings.machineColor       = '#a16a94'; // 0E - Magenta
Settings.woodColor          = '#cdab53'; // 0F - Brown
Settings.menuSelectionColor = '#01a252'; // 0B - Green
Settings.menuLineColor      = '#01a252'; // 0B - Green
Settings.menuTextColor      = '#01a252'; // 0B - Green
