Settings.blackColor    = '#3B3228'; // 00 - Black
Settings.enemyColor    = '#cb6077'; // 08 - Red
Settings.heroColor     = '#beb55b'; // 0B - Green
Settings.coinColor     = '#f4bc87'; // 0A - Yellow
Settings.waterColor    = '#8ab3b5'; // 0D - Blue
Settings.heartColor    = '#a89bb9'; // 0E - Magenta
Settings.tongueColor   = '#a89bb9'; // 0E - Magenta
Settings.friendColor   = '#7bbda4'; // 0C - Cyan
Settings.cloudColor    = '#f5eeeb'; // 07 - Bright White
Settings.landColor     = '#7e705a'; // 03 - Bright Black
Settings.rockColor     = '#b8afad'; // 04 - Grey
Settings.kidColor      = '#d28b71'; // 09 - Orange
Settings.machineColor  = '#a89bb9'; // 0E - Magenta
Settings.woodColor     = '#bb9584'; // 0F - Brown
