Settings.levelNameColor     = '#f5f5f5'; // 07 - Bright White
Settings.landBackground     = '#151515'; // 00 - Black
Settings.blackColor         = '#151515'; // 00 - Black
Settings.enemyColor         = '#ac4142'; // 08 - Red
Settings.heroColor          = '#90a959'; // 0B - Green
Settings.coinColor          = '#f4bf75'; // 0A - Yellow
Settings.waterColor         = '#6a9fb5'; // 0D - Blue
Settings.heartColor         = '#aa759f'; // 0E - Magenta
Settings.tongueColor        = '#aa759f'; // 0E - Magenta
Settings.friendColor        = '#75b5aa'; // 0C - Cyan
Settings.cloudColor         = '#f5f5f5'; // 07 - Bright White
Settings.landColor          = '#303030'; // 03 - Bright Black
Settings.rockColor          = '#b0b0b0'; // 04 - Grey
Settings.kidColor           = '#d28445'; // 09 - Orange
Settings.machineColor       = '#aa759f'; // 0E - Magenta
Settings.woodColor          = '#8f5536'; // 0F - Brown
Settings.menuSelectionColor = '#90a959'; // 0B - Green
Settings.menuLineColor      = '#90a959'; // 0B - Green
Settings.menuTextColor      = '#90a959'; // 0B - Green
