Settings.levelNameColor     = '#eff1f5'; // 07 - Bright White
Settings.landBackground     = '#2b303b'; // 00 - Black
Settings.blackColor         = '#2b303b'; // 00 - Black
Settings.enemyColor         = '#bf616a'; // 08 - Red
Settings.heroColor          = '#a3be8c'; // 0B - Green
Settings.coinColor          = '#ebcb8b'; // 0A - Yellow
Settings.waterColor         = '#8fa1b3'; // 0D - Blue
Settings.heartColor         = '#b48ead'; // 0E - Magenta
Settings.tongueColor        = '#b48ead'; // 0E - Magenta
Settings.friendColor        = '#96b5b4'; // 0C - Cyan
Settings.cloudColor         = '#eff1f5'; // 07 - Bright White
Settings.landColor          = '#4f5b66'; // 03 - Bright Black
Settings.rockColor          = '#a7adba'; // 04 - Grey
Settings.kidColor           = '#d08770'; // 09 - Orange
Settings.machineColor       = '#b48ead'; // 0E - Magenta
Settings.woodColor          = '#ab7967'; // 0F - Brown
Settings.menuSelectionColor = '#a3be8c'; // 0B - Green
Settings.menuLineColor      = '#a3be8c'; // 0B - Green
Settings.menuTextColor      = '#a3be8c'; // 0B - Green
