Settings.levelNameColor     = '#2d2d2d'; // 07 - Black
Settings.landBackground     = '#f2f0ec'; // 00 - Bright White
Settings.blackColor         = '#2d2d2d'; // 00 - Black
Settings.enemyColor         = '#f2777a'; // 08 - Red
Settings.heroColor          = '#99cc99'; // 0B - Green
Settings.coinColor          = '#ffcc66'; // 0A - Yellow
Settings.waterColor         = '#6699cc'; // 0D - Blue
Settings.heartColor         = '#cc99cc'; // 0E - Magenta
Settings.tongueColor        = '#cc99cc'; // 0E - Magenta
Settings.friendColor        = '#66cccc'; // 0C - Cyan
Settings.cloudColor         = '#f2f0ec'; // 07 - Bright White
Settings.landColor          = '#747369'; // 03 - Bright Black
Settings.rockColor          = '#a09f93'; // 04 - Grey
Settings.kidColor           = '#f99157'; // 09 - Orange
Settings.machineColor       = '#cc99cc'; // 0E - Magenta
Settings.woodColor          = '#d27b53'; // 0F - Brown
Settings.menuSelectionColor = '#99cc99'; // 0B - Green
Settings.menuLineColor      = '#99cc99'; // 0B - Green
Settings.menuTextColor      = '#99cc99'; // 0B - Green
