Settings.levelNameColor     = '#1d1f21'; // 07 - Black
Settings.landBackground     = '#ffffff'; // 00 - Bright White
Settings.blackColor         = '#1d1f21'; // 00 - Black
Settings.enemyColor         = '#cc6666'; // 08 - Red
Settings.heroColor          = '#b5bd68'; // 0B - Green
Settings.coinColor          = '#f0c674'; // 0A - Yellow
Settings.waterColor         = '#81a2be'; // 0D - Blue
Settings.heartColor         = '#b294bb'; // 0E - Magenta
Settings.tongueColor        = '#b294bb'; // 0E - Magenta
Settings.friendColor        = '#8abeb7'; // 0C - Cyan
Settings.cloudColor         = '#ffffff'; // 07 - Bright White
Settings.landColor          = '#969896'; // 03 - Bright Black
Settings.rockColor          = '#b4b7b4'; // 04 - Grey
Settings.kidColor           = '#de935f'; // 09 - Orange
Settings.machineColor       = '#b294bb'; // 0E - Magenta
Settings.woodColor          = '#a3685a'; // 0F - Brown
Settings.menuSelectionColor = '#b5bd68'; // 0B - Green
Settings.menuLineColor      = '#b5bd68'; // 0B - Green
Settings.menuTextColor      = '#b5bd68'; // 0B - Green
