Settings.levelNameColor     = '#272822'; // 07 - Black
Settings.landBackground     = '#f9f8f5'; // 00 - Bright White
Settings.blackColor         = '#272822'; // 00 - Black
Settings.enemyColor         = '#f92672'; // 08 - Red
Settings.heroColor          = '#a6e22e'; // 0B - Green
Settings.coinColor          = '#f4bf75'; // 0A - Yellow
Settings.waterColor         = '#66d9ef'; // 0D - Blue
Settings.heartColor         = '#ae81ff'; // 0E - Magenta
Settings.tongueColor        = '#ae81ff'; // 0E - Magenta
Settings.friendColor        = '#a1efe4'; // 0C - Cyan
Settings.cloudColor         = '#f9f8f5'; // 07 - Bright White
Settings.landColor          = '#75715e'; // 03 - Bright Black
Settings.rockColor          = '#a59f85'; // 04 - Grey
Settings.kidColor           = '#fd971f'; // 09 - Orange
Settings.machineColor       = '#ae81ff'; // 0E - Magenta
Settings.woodColor          = '#cc6633'; // 0F - Brown
Settings.menuSelectionColor = '#a6e22e'; // 0B - Green
Settings.menuLineColor      = '#a6e22e'; // 0B - Green
Settings.menuTextColor      = '#a6e22e'; // 0B - Green
