Settings.levelNameColor     = '#f9f9f9'; // 07 - Bright White
Settings.landBackground     = '#000000'; // 00 - Black
Settings.blackColor         = '#000000'; // 00 - Black
Settings.enemyColor         = '#e92f2f'; // 08 - Red
Settings.heroColor          = '#0ed839'; // 0B - Green
Settings.coinColor          = '#dddd13'; // 0A - Yellow
Settings.waterColor         = '#3b48e3'; // 0D - Blue
Settings.heartColor         = '#f996e2'; // 0E - Magenta
Settings.tongueColor        = '#f996e2'; // 0E - Magenta
Settings.friendColor        = '#23edda'; // 0C - Cyan
Settings.cloudColor         = '#f9f9f9'; // 07 - Bright White
Settings.landColor          = '#102015'; // 03 - Bright Black
Settings.rockColor          = '#555555'; // 04 - Grey
Settings.kidColor           = '#e09448'; // 09 - Orange
Settings.machineColor       = '#f996e2'; // 0E - Magenta
Settings.woodColor          = '#69542d'; // 0F - Brown
Settings.menuSelectionColor = '#0ed839'; // 0B - Green
Settings.menuLineColor      = '#0ed839'; // 0B - Green
Settings.menuTextColor      = '#0ed839'; // 0B - Green
